In [1]:
import numpy as np

In [2]:
ex_arr1 = np.array([1,2,3])
ex_arr1

array([1, 2, 3])

In [4]:
ex_arr2 = np.array([[1,2,3],[4,5,6]])
ex_arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
ex_arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ex_arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
### Access numpy array elements

In [8]:
ex_arr3[1,2]

6

In [10]:
## Get a specific row
ex_arr3[0,:]

array([1, 2, 3])

In [14]:
ex_arr3[:,1]

array([2, 5, 8])

In [16]:
## Change the value of an element

ex_arr3[2,1] = 88
ex_arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 88,  9]])